# stdin_open: true -> docker run -i
# tty: true        -> docker run -t

services:
    nginx:
        build: requirements/nginx
        ports:
            - "443:443"
        networks:
            - net_reverse_proxy
        stdin_open: true
        tty: true
        volumes:
            # - wordpress_files:${WORDPRESS_PATH}
            - /home/lzins/data/wordpress_files:${WORDPRESS_PATH}
        env_file:
            - ".env"
        # restart: on-failure
    db:
        build: requirements/db
        env_file: ".env"
        networks:
            - net_db
        stdin_open: true
        tty: true
        # volumes:
            # - wordpress_db:/var/lib/mysql/
            # - "/home/lzins/data/wordpress_db:/var/lib/mysql/"
        env_file:
            - ".env"
        # restart: on-failure
    wordpress:
        build: requirements/wordpress
        networks:
            - net_db
            - net_reverse_proxy
        stdin_open: true
        tty: true
        volumes:
            # - wordpress_files:${WORDPRESS_PATH}
            - /home/lzins/data/wordpress_files:${WORDPRESS_PATH}
        env_file:
            - ".env"
        # restart: on-failure

networks:
    net_reverse_proxy:
        driver: bridge
    net_db:
        driver: bridge

# volumes:
#     wordpress_db:
#         driver: local
#         driver_opts:
#             type: 'none'
#             o: 'bind'
#             device: '/home/lzins/data/wordpress_db'
#     wordpress_files:
#         driver: local
#         driver_opts:
#             type: 'none'
#             o: 'bind'
#             device: '/home/lzins/data/wordpress_files'
