services:
    nginx:
        build: requirements/nginx
        ports:
            - "443:443"
        networks:
            - net_reverse_proxy
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        # env_file: "requirements/nginx/nginx.env"
        # environment:
        #     - "MYSQL_USER=${MYSQL_USER}"
        #     - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        #     - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        #     - "WORDPRESS_DATABASE=${WORDPRESS_DATABASE}"
    db:
        build: requirements/db
        env_file: ".env"
        networks:
            - net_db
        stdin_open: true # docker run -i
        tty: true        # docker run -t
    wordpress:
        build: requirements/wordpress
        # env_file: ".env"
        networks:
            - net_db
            - net_reverse_proxy
        stdin_open: true # docker run -i
        tty: true        # docker run -t

networks:
    net_reverse_proxy:
        driver: bridge
    net_db:
        driver: bridge
