services:
    nginx:
        build: requirements/nginx
        ports:
            - "443:443"
        networks:
            - net_reverse_proxy
        stdin_open: true
        tty: true
        volumes:
            - "/home/lzins/data/wordpress_files:${WORDPRESS_PATH}"
        env_file:
            - ".env"
        restart: on-failure
    db:
        build: requirements/db
        env_file: ".env"
        networks:
            - net_db
        stdin_open: true
        tty: true
        volumes:
            - "/home/lzins/data/wordpress_db:${MYSQL_VOLUME_DEST}"
        env_file:
            - ".env"
        restart: on-failure
    wordpress:
        build: requirements/wordpress
        networks:
            - net_db
            - net_reverse_proxy
        stdin_open: true
        tty: true
        volumes:
            - "/home/lzins/data/wordpress_files:${WORDPRESS_PATH}"
        env_file:
            - ".env"
        restart: on-failure

networks:
    net_reverse_proxy:
        driver: bridge
    net_db:
        driver: bridge
